print("First code for testing")
print("Going to commit the changes for first time")
print("Going to commit the changes for Second time")
print("Going to commit the changes for third time")
print("Testing it for EC2 instance commit")
